resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/normful/flight-school
    branch: master

jobs:
- name: test-job
  plan:
  - get: flight-school
    trigger: true
  - task: a-test-task-within-this-build-plan
    file: flight-school/ci/build-task.yml
