# Pipeline
---

# Resource
resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/normful/flight-school
    branch: master

jobs:
  # Job
- name: test-job
  # Build Plan
  plan:
    # a `get` step
  - get: flight-school
    trigger: true
    # a `task` step
  - task: test-task
    file: flight-school/ci/build-task.yml
